#   _____ _                 _   _______ _      _        _
#  / ____(_)               | | |__   __(_)    | |      | |
# | (___  _ _ __ ___  _ __ | | ___| |   _  ___| | _____| |_
#  \___ \| | '_ ` _ \| '_ \| |/ _ \ |  | |/ __| |/ / _ \ __|
#  ____) | | | | | | | |_) | |  __/ |  | | (__|   <  __/ |_
# |_____/|_|_| |_| |_| .__/|_|\___|_|  |_|\___|_|\_\___|\__|
#                    | |
#                    |_|

#The default punishment duration in seconds
Default Duration: 3600

#The message that a user sees when they open a new ticket
FirstMessage: |2-

  §e Welcome to your ticket, to reply type /tr then your message!