name: Simple-Ticket
version: 1.0
author: BDX
main: com.ticket.SimpleTicket
api-version: 1.16

commands:

  newticket:
    description: Opens a Ticket
    usage: /<command>
    aliases: [ntick, nt]

  tickets:
    description: shows all tickets
    usage: /<command>
    aliases: [listtickets]

  ticket:
    description: Send messages in tickets
    usage: /<command> <message/args>
    aliases: [tr]

  treload:
    description: Reloads the Simple-Ticket config file settings
    usage: /<command>
    aliases: [ticketreload]

  tpunish:
    description: This command blocks a user from opening tickets for the given time
    usage: /<command> <player> <duration>
    aliases: [tban, tblock]

  tunpunish:
    description: This allows a punished member to open tickets again
    usage: /<command> <player>
    aliases: [tunmute, tunban, tfree]

  thist:
    description: This command shows the Simple-Ticket punishment history of a user
    usage: /<command> <player>
    aliases: [thistory]

  viewpunishments:
    description: This shows the names of all players who are currently punished
    usage: /<command>
    aliases: [tactivepunishments, tlive]

permissions:
  ticket.*:
    description: Permissions for Simple-Ticket
    children:
      ticket.ticket: true
      ticket.ticket.staff: true
      ticket.reload: true